### ISSUE TITLE
Merge dependabot PR's

### ISSUE THREAD

**Issue by dhreb** [Ash0x/CountriesDB#6]
- Let's get these open dependabot PR's merged and keep our dependencies up to date 👍

PR's:
https://github.com/Ash0x/CountriesDB/pull/5
https://github.com/Ash0x/CountriesDB/pull/4
https://github.com/Ash0x/CountriesDB/pull/3
https://github.com/Ash0x/CountriesDB/pull/2

**Comment by alxedelweiss** [comment]
Am I just seeing that 👀
